"use client";
import Link from "next/link";
import { FormEvent, Suspense, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Logo } from "@/components/Logo";
import { money, product } from "@/lib/product";
function CheckoutContent() {
  const params = useSearchParams(); const router = useRouter(); const gift = params.get("plan") === "gift";
  const qty = Math.max(1, Number(params.get("qty")) || 1); const unit = gift ? product.giftPrice : product.regularPrice;
  const [zone, setZone] = useState("inside"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const delivery = zone === "inside" ? 0 : 100; const total = useMemo(() => unit * qty + delivery, [unit, qty, delivery]);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); const values = Object.fromEntries(new FormData(e.currentTarget)); try { const response = await fetch("/api/order", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, productName: gift ? "Handmade Potli - Gift Package" : "Handmade Potli", quantity: qty, pricePerPiece: unit, deliveryFee: delivery, totalPrice: total }) }); const data = await response.json(); if (!response.ok) return setError(data.error || "We could not submit your order. Please try again."); sessionStorage.setItem("rg-loom-order", JSON.stringify({ orderId: data.orderId, productName: gift ? "Handmade Potli - Gift Package" : "Handmade Potli", quantity: qty, totalPrice: total })); router.push("/thank-you"); } catch { setError("We could not submit your order. Please try again."); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-[#fffaf6]"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><Logo /><Link href="/" className="text-sm font-bold text-plum">Back to shop</Link></header><div className="mx-auto grid max-w-5xl gap-8 px-5 pb-16 lg:grid-cols-[1.25fr_.75fr]"><form onSubmit={submit} className="rounded-[2rem] bg-white p-6 shadow-sm sm:p-9"><p className="text-sm font-bold uppercase tracking-[.18em] text-plum">Cash on delivery</p><h1 className="mt-3 font-serif text-4xl text-plum">Your delivery details</h1><p className="mt-3 text-stone-600">We will call you to confirm your order before delivery.</p><div className="mt-8 grid gap-5"><Field label="Full name" name="customerName" autoComplete="name" /><Field label="Phone number" name="phone" type="tel" autoComplete="tel" /><Field label="Email address" name="email" type="email" autoComplete="email" /><label className="grid gap-2 text-sm font-bold text-plum">Exact location<textarea required name="location" placeholder="Kindly share your exact location" className="min-h-24 rounded-xl border border-plum/15 p-3 font-normal text-stone-700 outline-none focus:border-plum" /></label><label className="grid gap-2 text-sm font-bold text-plum">Delivery area<select value={zone} onChange={e => setZone(e.target.value)} name="deliveryZone" className="rounded-xl border border-plum/15 p-3 font-normal text-stone-700 outline-none focus:border-plum"><option value="inside">Inside Kathmandu Valley - Free</option><option value="outside">Outside Kathmandu Valley - NPR 100</option></select></label></div>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-7 w-full rounded-full bg-plum px-6 py-4 font-bold text-white disabled:opacity-60">{loading ? "Submitting Order..." : "Order Now"}</button><p className="mt-4 text-center text-xs text-stone-500">Secure order · Cash on Delivery · 1-2 day delivery</p></form><aside className="h-fit rounded-[2rem] bg-pistachio p-6 sm:p-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-plum">Order summary</p><h2 className="mt-5 font-serif text-2xl text-plum">{gift ? "Gift Package" : "Handmade Potli"}</h2><p className="mt-2 text-sm text-stone-600">{gift ? "Premium package and personalised handwritten note." : "A one-of-a-kind handmade potli."}</p><div className="mt-6 space-y-3 border-y border-plum/15 py-5 text-sm"><div className="flex justify-between"><span>Price per piece</span><b>{money(unit)}</b></div><div className="flex justify-between"><span>Quantity</span><b>{qty}</b></div><div className="flex justify-between"><span>Delivery</span><b>{delivery ? money(delivery) : "Free"}</b></div></div><div className="mt-5 flex justify-between font-serif text-2xl text-plum"><span>Total</span><span>{money(total)}</span></div><p className="mt-6 text-sm text-stone-600">Payment method: <b>Cash on Delivery</b></p></aside></div></main>;
}
function Field({ label, name, type = "text", autoComplete }: { label: string; name: string; type?: string; autoComplete?: string }) { return <label className="grid gap-2 text-sm font-bold text-plum">{label}<input required name={name} type={type} autoComplete={autoComplete} className="rounded-xl border border-plum/15 p-3 font-normal text-stone-700 outline-none focus:border-plum" /></label>; }
export default function Checkout() { return <Suspense fallback={<main className="grid min-h-screen place-items-center bg-pistachio text-plum">Loading checkout…</main>}><CheckoutContent /></Suspense>; }
