import { google } from "googleapis";
import nodemailer from "nodemailer";
import { z } from "zod";
export const runtime = "nodejs";
const schema = z.object({ customerName: z.string().trim().min(2, "Please enter your name."), phone: z.string().trim().min(7, "Please enter a valid phone number."), email: z.string().email("Please enter a valid email."), location: z.string().trim().min(5, "Please enter your exact location."), deliveryZone: z.enum(["inside", "outside"]), productName: z.string().min(1), quantity: z.coerce.number().int().min(1), pricePerPiece: z.coerce.number().positive(), deliveryFee: z.coerce.number().min(0), totalPrice: z.coerce.number().positive() });
type Order = z.infer<typeof schema> & { orderId: string; dateTime: string };
const currency = (value: number) => `NPR ${value.toLocaleString("en-NP")}`;
function env(name: string) { const value = process.env[name]; if (!value) throw new Error(`Missing required server setting: ${name}`); return value; }
const headers = ["Order ID", "Date & Time", "Customer Name", "Phone Number", "Email Address", "Exact Location", "Product Name", "Quantity", "Price Per Piece", "Total Price", "Payment Method", "Order Status", "Notes"];
async function ensurePremiumSheet(sheets: ReturnType<typeof google.sheets>, spreadsheetId: string, tab: string) {
  const meta = await sheets.spreadsheets.get({ spreadsheetId, includeGridData: false });
  const sheet = meta.data.sheets?.find((item) => item.properties?.title === tab);
  if (!sheet?.properties?.sheetId && sheet?.properties?.sheetId !== 0) throw new Error(`Google Sheet tab \"${tab}\" was not found.`);
  const sheetId = sheet.properties.sheetId;
  const firstRow = await sheets.spreadsheets.values.get({ spreadsheetId, range: `'${tab}'!A1:M1` });
  if (!firstRow.data.values?.[0]?.[0]) await sheets.spreadsheets.values.update({ spreadsheetId, range: `'${tab}'!A1:M1`, valueInputOption: "RAW", requestBody: { values: [headers] } });
  await sheets.spreadsheets.batchUpdate({ spreadsheetId, requestBody: { requests: [
    { repeatCell: { range: { sheetId, startRowIndex: 0, endRowIndex: 1, startColumnIndex: 0, endColumnIndex: 13 }, cell: { userEnteredFormat: { backgroundColor: { red: 0.388, green: 0.106, blue: 0.251 }, textFormat: { foregroundColor: { red: 1, green: 1, blue: 1 }, bold: true, fontSize: 10 }, horizontalAlignment: "CENTER", verticalAlignment: "MIDDLE", wrapStrategy: "WRAP" } }, fields: "userEnteredFormat(backgroundColor,textFormat,horizontalAlignment,verticalAlignment,wrapStrategy)" } },
    { updateDimensionProperties: { range: { sheetId, dimension: "ROWS", startIndex: 0, endIndex: 1 }, properties: { pixelSize: 44 }, fields: "pixelSize" } },
    { updateDimensionProperties: { range: { sheetId, dimension: "COLUMNS", startIndex: 0, endIndex: 13 }, properties: { pixelSize: 130 }, fields: "pixelSize" } },
    { updateDimensionProperties: { range: { sheetId, dimension: "COLUMNS", startIndex: 5, endIndex: 6 }, properties: { pixelSize: 240 }, fields: "pixelSize" } },
    { updateDimensionProperties: { range: { sheetId, dimension: "COLUMNS", startIndex: 6, endIndex: 7 }, properties: { pixelSize: 200 }, fields: "pixelSize" } },
    { setBasicFilter: { filter: { range: { sheetId, startRowIndex: 0, startColumnIndex: 0, endColumnIndex: 13 } } } },
    { setDataValidation: { range: { sheetId, startRowIndex: 1, startColumnIndex: 11, endColumnIndex: 12 }, rule: { condition: { type: "ONE_OF_LIST", values: ["New Order", "Order Confirmed", "Order Ongoing", "Delivered", "Cancelled"].map((value) => ({ userEnteredValue: value })) }, strict: true, showCustomUi: true } } },
    { repeatCell: { range: { sheetId, startRowIndex: 1, startColumnIndex: 8, endColumnIndex: 10 }, cell: { userEnteredFormat: { numberFormat: { type: "CURRENCY", pattern: "NPR #,##0" } } }, fields: "userEnteredFormat.numberFormat" } }
  ] } });
}
async function saveToSheet(order: Order) { const auth = new google.auth.JWT({ email: env("GOOGLE_SERVICE_ACCOUNT_EMAIL"), key: env("GOOGLE_PRIVATE_KEY").replace(/\\n/g, "\n"), scopes: ["https://www.googleapis.com/auth/spreadsheets"] }); const sheets = google.sheets({ version: "v4", auth }); const tab = env("GOOGLE_SHEET_TAB_NAME"); const spreadsheetId = env("GOOGLE_SHEET_ID"); await ensurePremiumSheet(sheets, spreadsheetId, tab); await sheets.spreadsheets.values.append({ spreadsheetId, range: `'${tab}'!A:M`, valueInputOption: "USER_ENTERED", requestBody: { values: [[order.orderId, order.dateTime, order.customerName, order.phone, order.email, order.location, order.productName, order.quantity, order.pricePerPiece, order.totalPrice, "Cash On Delivery", "New Order", ""]] } }); }
function emailShell(title: string, content: string) { const brand = process.env.BRAND_NAME || "RG LOOM"; return `<!doctype html><html><body style="margin:0;background:#fff8f1;font-family:Arial,sans-serif;color:#34212d"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:32px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:auto;background:#fff;border-radius:24px;overflow:hidden"><tr><td style="background:#631b40;padding:28px;text-align:center;color:#fff"><div style="font-family:Georgia,serif;letter-spacing:3px;font-size:24px;font-weight:bold">${brand}</div><div style="color:#dfe0cc;margin-top:8px;font-size:12px;letter-spacing:2px">HANDMADE WITH A STORY</div></td></tr><tr><td style="padding:32px">${content}</td></tr><tr><td style="background:#dfe0cc;padding:18px;text-align:center;font-size:12px;color:#544451">© ${new Date().getFullYear()} ${brand}</td></tr></table></td></tr></table></body></html>`; }
const details = (o: Order) => `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:20px;border-collapse:collapse"><tr><td colspan="2" style="padding:12px;background:#dfe0cc;color:#631b40;font-weight:bold">ORDER DETAILS</td></tr>${[["Order ID", o.orderId], ["Product", o.productName], ["Quantity", String(o.quantity)], ["Price per piece", currency(o.pricePerPiece)], ["Delivery", o.deliveryFee ? currency(o.deliveryFee) : "Free"], ["Total", currency(o.totalPrice)]].map(([a,b]) => `<tr><td style="padding:10px;border-bottom:1px solid #eee">${a}</td><td style="padding:10px;border-bottom:1px solid #eee;text-align:right;font-weight:bold">${b}</td></tr>`).join("")}</table>`;
async function sendEmails(order: Order) { const transporter = nodemailer.createTransport({ host: env("SMTP_HOST"), port: Number(env("SMTP_PORT")), secure: Number(process.env.SMTP_PORT) === 465, auth: { user: env("SMTP_USER"), pass: env("SMTP_PASS") } }); const from = env("EMAIL_FROM"); const business = env("BUSINESS_EMAIL"); const businessHtml = emailShell("New order", `<h1 style="margin:0;color:#631b40;font-family:Georgia,serif">New order received</h1><p style="line-height:1.6">A new Cash On Delivery order arrived on ${order.dateTime}.</p><table role="presentation" width="100%"><tr><td style="padding:16px;background:#fff4f6;border-radius:12px"><b>Customer</b><br>${order.customerName}<br>${order.phone}<br>${order.email}<br>${order.location}</td></tr></table>${details(order)}<p style="margin-top:24px;padding:15px;background:#631b40;border-radius:12px;color:#fff"><b>New Order</b> · Please call the customer soon to confirm this order.</p>`); const customerHtml = emailShell("Order received", `<h1 style="margin:0;color:#631b40;font-family:Georgia,serif">Thank you, ${order.customerName}!</h1><p style="line-height:1.6">We have received your order successfully. Our sales representative will call you soon to confirm it.</p>${details(order)}<p style="margin-top:24px;color:#544451">Payment method: <b>Cash On Delivery</b><br>Need help? Reply to this email.</p><p>With love,<br><b>${process.env.BRAND_NAME || "RG LOOM"}</b></p>`); await transporter.sendMail({ from, to: business, replyTo: order.email, subject: `New Product Order Received - ${order.orderId}`, html: businessHtml }); await transporter.sendMail({ from, to: order.email, replyTo: process.env.BUSINESS_EMAIL, subject: `Your Order Has Been Received - ${process.env.BRAND_NAME || "RG LOOM"}`, html: customerHtml }); }
export async function POST(request: Request) { try { const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: parsed.error.issues[0]?.message || "Invalid order details." }, { status: 400 }); const order: Order = { ...parsed.data, orderId: `RG-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`, dateTime: new Intl.DateTimeFormat("en-NP", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kathmandu" }).format(new Date()) }; await saveToSheet(order); await sendEmails(order); return Response.json({ success: true, orderId: order.orderId }); } catch (error) { console.error("Order submission failed", error); return Response.json({ error: "Your order could not be completed. Please try again or contact us at 9843778195." }, { status: 500 }); } }
